name: Tests MyProject
on:
  push:
    branches:
       - main
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
      - name: Do tests
        uses: cd src && npm test
